### ISSUE TITLE
Feature Request: Debian 9 build support

### ISSUE THREAD

**Issue by mandeepsandhu** [facebook/mcrouter#219]
Support Debian **9** (stretch) as one of the build platforms.

**Comment by mandeepsandhu** [comment]
Current mcrouter build supports only boost `1.5x`. However Debian 9 comes with `1.62` installed. Can someone comment if it's okay to support the newer version of boost?

I'm planning on adding support for debian 9 build and would like to know if there are any objections to it.

mcrouter's `configure` script would need to be modified as well since it does not work correctly with `libboost1.62` (`folly`'s configure script seems to be doing the right thing though).

**Comment by kornrunner** [comment]
#225 should solve the configure thing, if merged in

**Comment by c4milo** [comment]
I'm currently having a hard time trying to compile mcrouter in Debian 9, here is the dockerfile with my current progress:  

```
FROM debian:stretch-slim

ENV MCROUTER_VERSION 0.36.0
ENV FOLLY_VERSION 2018.03.19.00
ENV WANGLE_VERSION 2018.03.19.00

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get install -y \
	build-essential \
	binutils-dev \
	autoconf \
	automake \
	pkg-config \
	python-dev \
	libdouble-conversion-dev \
	libgflags-dev \
	libjemalloc-dev \
	libgoogle-glog-dev \
	cmake \
	libboost-all-dev \
	libboost-context-dev \
	libevent-dev \
	libssl1.0-dev \
	libtool \
	zlib1g-dev \
	libsnappy-dev \
	liblzma-dev \
	libgtest-dev \
	curl \
	git \
	ragel \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /folly
RUN curl -Ls https://github.com/facebook/folly/archive/v${FOLLY_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cmake configure . \
	&& make \
	&& make install

WORKDIR /wangle
RUN curl -Ls https://github.com/facebook/wangle/archive/v${WANGLE_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cmake configure wangle \
	&& make \
	&& make install

WORKDIR /mcrouter
RUN curl -Ls https://github.com/facebook/mcrouter/archive/v${MCROUTER_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cd mcrouter \
	&& autoreconf --install \
	&& ./configure \
	&& make
```

**Comment by analbeard** [comment]
@c4milo did you get any further with this? I'm trying to build Debian packages and I have a packaged build of Folly, but I can't seem to package Wangle.

**Comment by c4milo** [comment]
@analbeard a little bit, my issue seemed to be caused by https://github.com/facebook/mcrouter/commit/a732a6623a1a03bc637cac9abb25f4a887762232
I then switched to building mcrouter from the HEAD of master and ran into this new issue: 

```
mv -f network/.deps/libmcrouter_a-AsciiSerialized.Tpo network/.deps/libmcrouter_a-AsciiSerialized.Po
g++ -DHAVE_CONFIG_H   -I../..   -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -MT network/libmcrouter_a-AsyncMcClientImpl.o -MD -MP -MF network/.deps/libmcrouter_a-AsyncMcClientImpl.Tpo -c -o network/libmcrouter_a-AsyncMcClientImpl.o `test -f 'network/AsyncMcClientImpl.cpp' || echo './'`network/AsyncMcClientImpl.cpp
network/AsyncMcClientImpl.cpp: In lambda function:
network/AsyncMcClientImpl.cpp:516:22: error: ‘class folly::AsyncSSLSocket’ has no member named ‘setSessionKey’; did you mean ‘sslSession_’?
           sslSocket->setSessionKey(serviceId);
                      ^~~~~~~~~~~~~
Makefile:1507: recipe for target 'network/libmcrouter_a-AsyncMcClientImpl.o' failed
make[3]: *** [network/libmcrouter_a-AsyncMcClientImpl.o] Error 1
make[3]: Leaving directory '/mcrouter/mcrouter/lib'
Makefile:1866: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/mcrouter/mcrouter/lib'
Makefile:1540: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mcrouter/mcrouter'
Makefile:669: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c cd mcrouter 	&& autoreconf --install 	&& ./configure 	&& make' returned a non-zero code: 2
```

**Comment by c4milo** [comment]
I also just tried with the recently released v0.37.0 version, by @andreazevedo, and I get the following: 

```
ranlib libtest_util.a
g++ -DHAVE_CONFIG_H   -I../../..   -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -MT test/mock_mc_server-MockMc.o -MD -MP -MF test/.deps/mock_mc_server-MockMc.Tpo -c -o test/mock_mc_server-MockMc.o `test -f 'test/MockMc.cpp' || echo './'`test/MockMc.cpp
test/MockMc.cpp: In member function ‘std::pair<const facebook::memcache::MockMc::Item*, long unsigned int> facebook::memcache::MockMc::leaseGet(folly::StringPiece)’:
test/MockMc.cpp:166:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
mv -f test/.deps/mock_mc_server-MockMc.Tpo test/.deps/mock_mc_server-MockMc.Po
g++ -DHAVE_CONFIG_H   -I../../..   -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -MT test/mock_mc_server-MockMcServer.o -MD -MP -MF test/.deps/mock_mc_server-MockMcServer.Tpo -c -o test/mock_mc_server-MockMcServer.o `test -f 'test/MockMcServer.cpp' || echo './'`test/MockMcServer.cpp
mv -f test/.deps/mock_mc_server-MockMcServer.Tpo test/.deps/mock_mc_server-MockMcServer.Po
/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2   -o mock_mc_server test/mock_mc_server-MockMc.o test/mock_mc_server-MockMcServer.o ../../lib/libmcrouter.a -lwangle -lfolly -ldouble-conversion -lz -lssl -lcrypto -levent -lgflags -lglog  -L/usr/lib/x86_64-linux-gnu  -lboost_filesystem       -lboost_program_options -lboost_system -lboost_regex       -lboost_thread -lpthread -pthread
libtool: link: g++ -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -o mock_mc_server test/mock_mc_server-MockMc.o test/mock_mc_server-MockMcServer.o -pthread  ../../lib/libmcrouter.a -lwangle -lfolly -ldouble-conversion -lz -lssl -lcrypto -levent -lgflags -lglog -L/usr/lib/x86_64-linux-gnu -lboost_filesystem -lboost_program_options -lboost_system -lboost_regex -lboost_thread -lpthread -pthread
/usr/bin/ld: //usr/local/lib/libfolly.a(CacheLocality.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:486: recipe for target 'mock_mc_server' failed
make[4]: Leaving directory '/mcrouter/mcrouter/lib/network'
make[4]: *** [mock_mc_server] Error 1
make[3]: *** [all-recursive] Error 1
Makefile:594: recipe for target 'all-recursive' failed
make[3]: Leaving directory '/mcrouter/mcrouter/lib/network'
Makefile:1848: recipe for target 'all-recursive' failed
make[2]: Leaving directory '/mcrouter/mcrouter/lib'
make[2]: *** [all-recursive] Error 1
Makefile:1540: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/mcrouter/mcrouter'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Makefile:669: recipe for target 'all' failed
The command '/bin/sh -c cd mcrouter 	&& autoreconf --install 	&& ./configure 	&& make' returned a non-zero code: 2
```

### Dockerfile to reproduce
```dockerfile
FROM debian:stretch-slim

ENV MCROUTER_VERSION v0.37.0
ENV FOLLY_VERSION v2018.03.19.00
ENV WANGLE_VERSION v2018.03.19.00

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get install -y \
	build-essential \
	binutils-dev \
	autoconf \
	automake \
	pkg-config \
	python-dev \
	libdouble-conversion-dev \
	libgflags-dev \
	libjemalloc-dev \
	libgoogle-glog-dev \
	cmake \
	libboost-all-dev \
	libboost-context-dev \
	libevent-dev \
	libssl1.0-dev \
	libtool \
	zlib1g-dev \
	libsnappy-dev \
	liblzma-dev \
	libgtest-dev \
	curl \
	git \
	ragel \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /folly
RUN curl -Ls https://github.com/facebook/folly/archive/${FOLLY_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cmake configure . \
	&& make \
	&& make install

WORKDIR /wangle
RUN curl -Ls https://github.com/facebook/wangle/archive/${WANGLE_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cmake configure wangle \
	&& make \
	&& make install

WORKDIR /mcrouter
RUN curl -Ls https://github.com/facebook/mcrouter/archive/${MCROUTER_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cd mcrouter \
	&& autoreconf --install \
	&& ./configure \
	&& make
```

**Comment by c4milo** [comment]
Here is the final Debian 9 Stretch Dockerfile I was able to produce: 

```dockerfile
FROM debian:stretch-slim

ENV MCROUTER_VERSION master
ENV FOLLY_VERSION v2018.03.26.00
ENV WANGLE_VERSION v2018.03.26.00

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get install -y \
	build-essential \
	binutils-dev \
	autoconf \
	automake \
	pkg-config \
	python-dev \
	libdouble-conversion-dev \
	libgflags-dev \
	libjemalloc-dev \
	libgoogle-glog-dev \
	cmake \
	libboost-all-dev \
	libboost-context-dev \
	libevent-dev \
	libssl1.0-dev \
	libtool \
	zlib1g-dev \
	libsnappy-dev \
	liblzma-dev \
	libgtest-dev \
	curl \
	git \
	ragel \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /folly
RUN curl -Ls https://github.com/facebook/folly/archive/${FOLLY_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cmake configure . \
	&& make \
	&& make install

WORKDIR /wangle
RUN curl -Ls https://github.com/facebook/wangle/archive/${WANGLE_VERSION}.tar.gz | tar xvzf - --strip-components=1
RUN cmake configure wangle \
	&& make \
	&& make install

WORKDIR /mcrouter
RUN curl -Ls https://github.com/facebook/mcrouter/archive/${MCROUTER_VERSION}.tar.gz | tar xvzf - --strip-components=1
ADD folly.patch .
RUN git apply folly.patch \
	&& cd mcrouter \
	&& autoreconf --install \
	&& ./configure \
	&& make VERBOSE=1

FROM debian:stretch-slim
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get install -y \
	libssl1.0.2 \
	libevent-2.0-5 \
	libgflags2v5 \
	libgoogle-glog0v5 \
	libboost-context1.62.0 \
	libboost-filesystem1.62.0 \
	libboost-program-options1.62.0 \
	libboost-system1.62.0 \
	libboost-regex1.62.0 \
	libboost-thread1.62.0 \
	libdouble-conversion1

COPY --from=0 /mcrouter/mcrouter/mcrouter .

CMD ["./mcrouter"]
```
