### ISSUE TITLE
Failed to build on ubuntu18.04

### ISSUE THREAD

**Issue by hoody17** [facebook/mcrouter#414]
i use the script in /mcrouter/script/
and command is $./install_ubuntu_18.04.sh /home/$USER/mcrouter-install/ -j4
the error is
/usr/include/c++/7/bits/stl_construct.h:75:7: error: ‘folly::File::File(const folly::File&)’ is private within this context
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/hudi/mcrouter_install/pkgs/folly/folly/io/ShutdownSocketSet.h:22:0,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/AsyncSocket.h:31,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/fdsock/AsyncFdSocket.h:21,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/fdsock/AsyncFdSocket.cpp:17:
/home/hudi/mcrouter_install/pkgs/folly/folly/File.h:160:3: note: declared private here
   File(const File&) = delete;
   ^~~~
In file included from /usr/include/c++/7/memory:64:0,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/AsyncSocket.h:23,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/fdsock/AsyncFdSocket.h:21,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/fdsock/AsyncFdSocket.cpp:17:
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function ‘folly::File::File(const folly::File&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/hudi/mcrouter_install/pkgs/folly/folly/io/ShutdownSocketSet.h:22:0,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/AsyncSocket.h:31,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/fdsock/AsyncFdSocket.h:21,
                 from /home/hudi/mcrouter_install/pkgs/folly/folly/io/async/fdsock/AsyncFdSocket.cpp:17:
/home/hudi/mcrouter_install/pkgs/folly/folly/File.h:160:3: note: declared here
   File(const File&) = delete;
how can i resolve it?
