### ISSUE TITLE
Mcrouter compiler error

### ISSUE THREAD

**Issue by dzhyw** [facebook/mcrouter#191]
Ubuntu 14.04.5 LTS

cd  /usr/local/src/mcrouter-master/mcrouter/scripts
./install_ubuntu_14.04.sh /usr/local/mcrouter/ -j4

output error:

In file included from ./../folly/String.h:40:0,
                 from ./../folly/Format.h:27,
                 from ./../folly/dynamic-inl.h:24,
                 from ./../folly/dynamic.h:580,
                 from dynamic.cpp:17:
./../folly/FBVector.h: In lambda function:
./../folly/FBVector.h:1432:49: error: parameter packs not expanded with '...':
           M_construct(start, std::forward<Args>(args)...);
                                                 ^
./../folly/FBVector.h:1432:49: note:         'args'
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [dynamic.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [ExceptionWrapper.lo] Error 1
In file included from ./../folly/String.h:40:0,
                 from ./../folly/Format.h:27,
                 from File.cpp:22:
./../folly/FBVector.h: In lambda function:
./../folly/FBVector.h:1432:49: error: parameter packs not expanded with '...':
           M_construct(start, std::forward<Args>(args)...);
                                                 ^
./../folly/FBVector.h:1432:49: note:         'args'
make[2]: *** [File.lo] Error 1
make[2]: Leaving directory `/usr/local/mcrouter/pkgs/folly/folly'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/mcrouter/pkgs/folly/folly'
make: *** [all] Error 2

How to fix, mcrouter compiler in the end what kind of dependency? Is there a specific list?

**Comment by jmswen** [comment]
Hi @dzhyw, as of recently, mcrouter requires a compiler with some reasonable support for C++14.  (folly, the biggest dependency of mcrouter, now uses C++14 features liberally.)  Ubuntu 14 ships with gcc-4.8, and we now need at least gcc-4.9 to compile mcrouter and folly.  (This is the same reason our Travis build has been broken recently.)  

We will update our install script for Ubuntu 14 (https://github.com/facebook/mcrouter/blob/master/mcrouter/scripts/install_ubuntu_14.04.sh) accordingly and make it more clear on the Wiki what mcrouter requires for installation.

**Comment by andreazevedo** [comment]
Hello @dzhyw,
It is also important to use a release branch (e.g. https://github.com/facebook/mcrouter/commits/release-36-0). Release 36 should build and work correctly on Ubuntu 14.04.

**Comment by dzhyw** [comment]
Thank's all , according to your method, the current installation was successful.
