### PR TITLE
Fix autotools build

### LINKED ISSUE #444: folly build error
Hello
[there is some problem with fmt and folly](https://github.com/facebook/mcrouter/actions/runs/8574837660/job/23502521521#step:3:1929). 
Facebook Katran had the same issue and [they also updated fmt package as well.](https://github.com/facebookincubator/katran/issues/225)

### LINKED ISSUE #447: Failed to build on Ubuntu 24.04
Anyone can provide the build script for Ubuntu 24.04?

### LINKED ISSUE #453: master is broken because of missing include ClientIdentifierHelper.h
2f32271533fdf54ce71cfb65f6fda3c621f076a4 added an include `core_infra_security/thrift_authentication_module/detail/ClientIdentifierHelper.h` in `ServerOnRequest.h`, which is probably internal to Facebook and not shipped anywhere.

```
sccache clang++-16 -DHAVE_CONFIG_H   -I..
-I/cfsetup_build/mcrouter/build/install/include
-DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION
-Wno-missing-field-initializers -Wno-deprecated-declarations -W -Wall
-Wextra -Wno-unused-parameter -fno-strict-aliasing -std=c++20 -g -O2
-MT mcrouter-main.o -MD -MP -MF .deps/mcrouter-main.Tpo -c -o
mcrouter-main.o `test -f 'main.cpp' || echo './'`main.cpp
In file included from main.cpp:21:
In file included from ../mcrouter/StandaloneUtils.h:13:
In file included from ../mcrouter/Server.h:42:
In file included from ./Server-inl.h:23:
../mcrouter/ServerOnRequest.h:14:10: fatal error:
'core_infra_security/thrift_authentication_module/detail/ClientIdentifierHelper.h'
file not found
#include "core_infra_security/thrift_authentication_module/detail/ClientIdentifierHelper.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [Makefile:2055: mcrouter-main.o] Error 1
```

### PR DESCRIPTION
**Pull request by mszabo-wikia**
The OSS autotools build has been nonfunctional for about a year. While #449 would be a better long-term approach to fixing the build since it would also bring it in sync with other Meta OSS projects and enable testing in CI, fixing the existing build until there's movement on that front would at least provide a signal on whether the OSS version is buildable at all.

So:
* Introduce new Ubuntu 24.04 build files and use them in CI. I'll remove build files, Dockerfiles etc. for ancient Ubuntu and CentOS versions in a followup PR.
* Pin fmtlib to 11.0.2, like fbcode_builder does, and skip building its test suite to not waste time.
* Use Ninja to generate and build CMake-based dependencies.
* Use googletest, gmock and zstd as packaged by Ubuntu rather than building their older versions from source.
* Introduce and use a new define `MCROUTER_OSS_BUILD` to mark OSS-specific conditional compilation blocks. This could probably replace the existing `LIBMC_FBTRACE_DISABLE` and `DISABLE_COMPRESSION` defines too, as long as those aren't used outside of the OSS build.
* Fix OSS build failures that have gone undetected due to CI being broken:
  * Add a shim for the SR-specific method `HostInfoLocation::hostUniqueKey` (used since 85facb9200dea75e661447ed11e05806f42de65f).
  * Remove redundant CarbonRouterInstance deletion logging that was using a Meta-specific include (used since 6c2142acd8e69edd40eed70a93ea17ee2909287d).
  * Disable client identity propagation in the OSS build since it relies on Meta-specific code (used since 2f32271533fdf54ce71cfb65f6fda3c621f076a4).

Fixes #453, fixes #444, fixes #447 etc.

### CODE REVIEW

File: mcrouter/CarbonRouterInstance-inl.h [hunk 1]
```diff
@@ -131,7 +133,11 @@ CarbonRouterInstance<RouterInfo>* CarbonRouterInstance<RouterInfo>::createRaw(
 
   // Deleter is only called if unique_ptr::get() returns non-null.
   auto deleter = [](CarbonRouterInstance<RouterInfo>* inst) {
+#ifdef MCROUTER_OSS_BUILD
+    FB_LOG_EVERY_MS(WARNING, 10000) << "Destroying CarbonRouterInstance";
+#else
     LOG_EVERY_MS(WARNING, 10000) << "Destroying CarbonRouterInstance";
```
Comment (disylh) [inline mcrouter/CarbonRouterInstance-inl.h:139]: This logging is not important so could be remove entirely.

**Review by disylh — CHANGES_REQUESTED** [review]

File: mcrouter/CarbonRouterInstance-inl.h (hunk 1 above)
Comment (mszabo-wikia) [reply mcrouter/CarbonRouterInstance-inl.h]: Done in 2b8cbd46—the custom deleter will probably still be necessary though, since the `CarbonRouterInstance` destructor is private which precludes using std::default_deleter.

Comment (disylh) [reply mcrouter/CarbonRouterInstance-inl.h]: Yes custom deleter is needed. Thanks for fixing the OSS build!
